### ISSUE TITLE
eslint-loader with WebPack 2.2

### ISSUE THREAD

**Issue by jeffrey-l-turner** [MoOx/eslint-loader#148]
I am unable to get the failOnWarning and failOnError properties to work with WebPack 2.2. The newer version of WebPack does not recognize 'eslint' or 'eslint-loader' as a top level property on the webpack.config.js file. I've also tried using those properties in the enforce: 'pre' section of the rules. Is there a new way to specify this with the new version of WebPack. Thanks.

**Comment by bebraw** [comment]
@jeffrey-l-turner Top level configuration isn't supported anymore. Something known as [LoaderOptionsPlugin](https://webpack.js.org/guides/migrating/#loaderoptionsplugin-context) replaced it.

**Comment by MoOx** [comment]
Alternatively, this loader accepts parameters in each loader config.

**Comment by jeffrey-l-turner** [comment]
ok for everyone else's edification per [#457](https://github.com/vuejs-templates/webpack/issues/457) as a temporary fix, above, here's what I did and it works:

```
webpack = require('webpack');
...
plugins: [
        new webpack.LoaderOptionsPlugin({
            options: {
                eslint:
                {
                    failOnWarning: false,
                    failOnError: false,
                    fix: false,
                    quiet: false,
                },
            },
        }),
    ],
````

**Comment by shssoichiro** [comment]
Unfortunately I wasn't able to get this to work even with the above workaround.

**Comment by MoOx** [comment]
You don't need a workaround. Just pass option directly with the loader. I will try to update the doc accordingly.

**Comment by shssoichiro** [comment]
Do you mean something like this?

```
{
    test: /\.js$/,
    enforce: 'pre',
    exclude: /(node_modules|bower_components|\.spec\.js)/,
    use: [
        {
            loader: 'eslint-loader',
            options: {
                failOnWarning: false,
                failOnError: false
            }
        }
    ]
},
```

I'm trying this but eslint loader still causes npm to return an error code. I'm using eslint-loader 1.6.1 with webpack 2.2.1 final.

**Comment by maciej-gurban** [comment]
Neither of provided solution worked for me with webpack 2.

**Comment by Tsvetkovv** [comment]
@maciej-gurban the same issue

**Comment by shssoichiro** [comment]
I've tracked down the issue to the fact that, in webpack 2, any use of `emitError`, which eslint-loader calls, will cause webpack to return an exit code of 2, which is an error. However, I'm not familiar enough with the inner workings of either library to suggest a fix.

The workaround is to set any lints which are not critical to `warn` instead of `error`.

Also to note, the actual *build* still finishes and produces output. This only affects wrappers that would call webpack, such as `webpack-dev-server` (won't automatically reload the browser if lint errors exist) or `frontend-maven-plugin` (will fail the maven build if lint errors exist).
