### ISSUE TITLE
mkdirp module cannot be found

### ISSUE THREAD

**Issue by davazp** [MoOx/eslint-loader#166]
The problem affects the latest release.  It seems caused by the recently added `loader-fs-cache` dependency, which does not include `mkdirp` in the dependency list  (but it uses it).

I have reported it viankakrisna/loader-fs-cache#1, but I created this issue for people experiencing the same problem.

**Comment by jeremywiebe** [comment]
I've just run into this problem also.  Given that this `1.7.0` release is obviously broken, would it be possible to roll back the `loader-fs-cache` and release `1.7.1` and then iron out the issues in this bug report?  

Right now this is completely breaking `eslint-loader`.

/cc @MoOx @viankakrisna

**Comment by viankakrisna** [comment]
Sorry for the breakage! it's now released as 1.0.1

**Comment by MoOx** [comment]
@davazp @jeremywiebe In this kind of scenario, the best thing to do is to use ~1.6.0 so you don't get the "bug". Reverting an improvement because of a small thing that you can workaround by having mkdir around or using an old version look crazy to me. Opening a PR to add the missing dep will take the same time as commenting here btw.

@viankakrisna no problem, this kind of things happen :) Thanks for fixing this quickly!

**Comment by jeremywiebe** [comment]
@viankakrisna that was fast!  Thank you.
