### ISSUE TITLE
Eslint errors are shown as warnings on console and webpack 2 build doesn't fail even with failOnError as true.

### ISSUE THREAD

**Issue by AjayU** [MoOx/eslint-loader#198]
I have configured eslint loader to be used with webpack 2 with below options. 
{
	test: /\.js$/,
	enforce: 'pre',
	loader: 'eslint-loader',
	exclude: /node_modules|build|testApplication/,
	include : [paths.source],
	options: {
		cache:true,
		configFile: path.join(__dirname, 'eslintRules.json'),
		"ignorePath":path.join(__dirname, 'eslintFolders.ignore'),
		cwd:path.resolve(process.cwd(), '.'),
		failOnError :true,
		formatter: require('eslint/lib/formatters/table')
	},
}
My npm react project structure is 
module1/
               component1
module2/
               component2
module3/
               component3
commonfile1
commonfile2
app/
        appfile1
        appfile2

Scenario 1: If there is some eslint error in appfile1 or appfile2 the webpack build fails with eslint printing the first file on which the error code was present.
Scenario 2: If I ignore the app folder in the ignore file and execute the build. The eslint build succedds with  printing the messages along with rule as error but the module failed message shown as WARNING in 'filepath' instead of ERROR in 'filepath'. If I have a lot of files with the similar rule failure the build fails with "WARNING in filepath" message for some and "ERROR in filepath" message for some files.

I expected this to be consistent so that build fails even if there is an error in code at any level of module component.

I also tried with emitError:true in options but still getting the same output.

Would you recommend some other options i could try or any version conflict of eslint/webpack causing this?
Below is the list of dependencies versions
"eslint": "^4.5.0",
"eslint-loader": "^1.9.0",
"eslint-plugin-import": "^2.7.0",
"eslint-plugin-react": "^7.2.1",
"webpack": "^3.5.5",

**Comment by MoOx** [comment]
If errors as show as warnings, this cannot trigger a build fail.
You must succeed to have eslint errors as webpack errors.
This module is covered by tests to ensure this behavior is stable so you might try to double check your config or provide a failing test (which will help more than your explanation to provide a fix)

**Comment by vepanimas** [comment]
@AjayU, have you found a solution? I faced the same issue right now and don't know what to do. 
I'm really sorry for writing in a closed issue, but this is the only relevant I found.

**Comment by vepanimas** [comment]
@MoOx, it looks that I found the reason of errors treated as warnings. Let's start with a test:

**test/require-context.js**
```js
var test = require("ava")
var webpack = require("webpack")
var conf = require("./utils/conf")

test.cb("eslint-loader can return error if file is bad and required as context module", function(t) {
  t.plan(1)
  webpack(conf(
    {
      entry: "./test/fixtures/require-context.js",
    },
    {
      failOnError: true,
    }),
  function(err, stats) {
    if (err) {
      throw err
    }

    t.true(
      stats.hasErrors(),
      "a file that contains eslint errors should return error"
    )
    t.end()
  })
})
```

**/test/fixtures/require-context.js**
```js
const context = require.context(".", false, /error\.js$/)
context.keys().forEach(function(key) {
  context(key)
})
```

**test/fixtures/error.js**
```js
var foo = stuff
```

This test would fail.

If an error exists in `error.js`, it will be emited to `compilation.modules['module-id'].errors` collection, but on the compilation instance it would be located in `compilations.warnings`. So, `stats.hasErrors()` will return `false`. And `NoEmitOnErrorsPlugin` will emit all assets, because its implementation relies on `stats.hasErrors` method. As a result, we are in a bad situation when our assets failed syntax check, but we don't know about that.

This behavior is caused by context modules which are "optional" in webpack and errors occured in them treated as warnings. [Here](https://github.com/webpack/webpack/blob/master/lib/Compilation.js#L157) we can find an example.

I wrote a simple plugin which solves this issue. It moves the optional module errors from `compilation.warnings` to `compilation.errors`. But it seems a little tricky and I believe it can lead to unpredictable consequences.

```js
class OptionalModulesErrorsPlugin {
  apply(compiler) {
    compiler.plugin("after-compile", (compilation, callback) => {
      compilation.modules
        .filter(module => module.optional && module.errors.length > 0)
        .forEach(module => {
          module.errors.forEach(err => {
            const warningId = compilation.warnings.indexOf(err)
            if (warningId !== -1) {
              compilation.warnings.splice(warningId, 1)
              compilation.errors.push(err)
            }
          })
        })

      callback()
    })
  }
}
```

**Comment by cms26** [comment]
I ran into the same issue and vepanima's comment helped resolve it. @vepanimas, do you think this is a bug and perhaps this issue should be reopened? If this is not a bug perhaps this would be nice to add to the Gotchas section in the readme file. Just wondering. :)

**Comment by vepanimas** [comment]
@cms26, I don't know if this is a bug, it looks more like a webpack feature. But it is really confusing and hard to notice when some of your invalid source files don't emit errors. I believe that a plugin itself should handle this case properly. @MoOx , what do you think?
