### ISSUE TITLE
peer dependencies can be changed to plain dependencies as of npm3

### ISSUE THREAD

**Issue by Pomax** [MoOx/eslint-loader#72]
Because of how npm3 puts all modules at the root level unless there's a versioning conflict, `peerDependencies` can be moved in the `dependencies` section, so that they'll install if they're not already available, but skipped if already installed (matching what the original peer dependency in npm2 and below did)

**Comment by nkbt** [comment]
Peer deps are not deprecated and libraries are encouraged to use them to give devs more freedom. So devs can potentially use incompatible versions that can still work well.

Dependencies work in a different way and do not suit for writing small libs/plugins.

**Comment by MoOx** [comment]
Agree with @nkbt.

**Comment by Pomax** [comment]
Wait, no they don't? As far as the docs surrounding NPM3 suggest, peer dependencies and plain dependencies now work exactly the same. Version conflicts are simply resolved by giving the module that needs a conflicting version w.r.t. the version already found at the root level its own local `./node_modules` dir, which solves the conflict due to how dependency resolution still happens bottom-up (so local >> root >> system cache).

**Comment by nkbt** [comment]
@Pomax this is not how dependencies and peerDependencies work. Peer dependencies do not resolve themselves for a library if version is incompatible with end-product. Dependencies do. Which means you end up with, for example, two React libraries in your project if you use dependencies instead of peer ones. With peer deps you as a developer will decide if you are ok with using incompatible peer dep (that is used in your product), and that might work out well.

**Comment by Pomax** [comment]
I see, thanks.

**Comment by nkbt** [comment]
np :ok_hand:
